MAINT, CI: check _distributor_init.py contents
* following on from continued problems reported here:
https://github.com/scipy/scipy/issues/15050

* draft in code to check that MacOS wheels get
the same `_distributor_init.py` as the one present
in the wheels repo, rather than the generic nearly-empty
copy actually present in the `1.7.3` release

* we've had two pull requests about this and it slipped through into
a release despite 3 sets of eyes so need to be careful here;
I'd like to the test script added here failing for MacOS in CI
like it does locally, before attempting a fix

* this is likely still wip, since relative paths/directories
can be confusing to predict in the wheels/multibuild control
flow, which also flushes in and out of containers I think, etc.
(this probably contributed to the original problem)

* the script did seem to work in a quick local check though, complaining
about our new MacOS file inclusion, but happy with the long-standing
windows wheel inclusion for dirs containing wheels for each OS type:

`python verify_init.py /Users/treddy/rough_work/scipy/release_173/release/installers/windows`
`python verify_init.py /Users/treddy/rough_work/scipy/release_173/release/installers/linux`
`python verify_init.py /Users/treddy/rough_work/scipy/release_173/release/installers/mac`

```
Traceback (most recent call last):
  File "verify_init.py", line 40, in <module>
    check_for_dist_init(input_dir=input_dir)
  File "verify_init.py", line 34, in check_for_dist_init
    raise ValueError(f"Contents of _distributor_init.py incorrect for
{wheel_file}")
ValueError: Contents of _distributor_init.py incorrect for
/Users/treddy/rough_work/scipy/release_173/release/installers/mac/scipy-1.7.3-cp39-cp39-macosx_10_9_x86_64.whl
```